language: php

php:
  - 5.3.3

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  # Install apache
  - sudo apt-get update
  - sudo apt-get install apache2
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://raw.github.com/gist/16d751c979fdeb5a14e3/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://raw.github.com/gist/2eb301570ed4a1f4c33d/gistfile1.txt)" | sed -e "s,PATH,`pwd`/www,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 restart
  - sudo sh -c "echo 127.0.1.1	lincoln.local >> /etc/hosts"
  - sudo sh -c "cat openscholar/behat/lincoln-vhost.txt > /etc/apache2/sites-available/lincoln"
  - sudo a2ensite lincoln
  - sudo service apache2 reload
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - bash scripts/setup
  - bash scripts/build
  # Install a multi-tanent, developemnt site.
  - cd www
  - mkdir -p /tmp/devel-mails
  - sudo chmod 777 /tmp -R
  - drush si openscholar --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal openscholar_flavor_form.os_profile_flavor=development openscholar_install_type.os_profile_type=vsite --yes
  - drush vset purl_base_domain http://127.0.0.1
  - drush en os_migrate_demo -y
  - drush mi --all --user=1


  # Copy Behat configuration file.
  - cd profiles/openscholar/behat
  - cp behat.local.yml.travis behat.local.yml
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --prefer-source

script:
    - ./bin/behat --tags=~wip
