language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  # Install apache
  - sudo apt-get update
  - sudo apt-get install apache2
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/74f4fec92c064c4f683fef28a6098caf0f038de7/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/2eb301570ed4a1f4c33d/raw/8066fda124b6c86f69ad32a010b8c22bbaf868e8/gistfile1.txt)" | sed -e "s,PATH,`pwd`/www,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 restart
  - sudo sh -c "echo 127.0.1.1	lincoln.local >> /etc/hosts"
  - sudo sh -c "cat openscholar/behat/lincoln-vhost.txt > /etc/apache2/sites-available/lincoln"
  - sudo a2ensite lincoln
  - sudo service apache2 reload
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - bash scripts/setup
  - bash scripts/build

  # Download and install Apache solr
  - wget http://wiki.gizra-labs.com/images/e/ee/Apache-solr-3.6.2.zip
  - unzip -o Apache-solr-3.6.2.zip
  - cd apache-solr-3.6.2/example/solr/conf
  # Copy the solr config files from the apache solr module
  - yes | cp /home/travis/build/openscholar/openscholar/www/profiles/openscholar/modules/contrib/apachesolr/solr-conf/solr-3.x/* .
  # Copy the modified solrconfig.xml file to commit records every 20 seconds so items will show up in search sooner
  - yes | cp /home/travis/build/openscholar/openscholar/www/profiles/openscholar/behat/solr/solrconfig.xml .
  - cd ../../
  - java -jar start.jar &
  - sleep 10
  - cd /home/travis/build/openscholar/openscholar

  # Install a multi-tanent, development site.
  - cd www
  - mkdir -p /tmp
  - mkdir -p /tmp/devel-mails
  - mkdir -p sites/default/files
  - sudo chmod 777 /tmp -R
  - sudo chmod 777 sites/default -R
  - drush si openscholar --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal openscholar_flavor_form.os_profile_flavor=development openscholar_install_type.os_profile_type=vsite --yes
  - drush vset purl_base_domain http://127.0.0.1
  - drush en os_migrate_demo -y
  - drush mi --all --user=1

  # Index site using Apache solr
  - drush en os_search_solr -y
  - drush solr-mark-all
  - drush solr-index

  # Make sure emails are not sent.
  - php -r "print json_encode(array('default-system' => 'DevelMailLog', 'mimemail' => 'MimeMailSystem'));" | drush vset --format=json mail_system -

  # Copy Behat configuration file.
  - cd profiles/openscholar/behat
  - cp behat.local.yml.travis behat.local.yml
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --prefer-source
  - sudo cat /var/log/apache2/error.log

script:
  - ./bin/behat --tags=~wip

after_script:
    - sudo cat /var/log/apache2/error.log
